[project]
name = "transformers-the-definitive-guide"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ohmycloud", email = "ohmycloudy@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "transformers>=5.17.0",
]

[project.scripts]
transformers-the-definitive-guide = "transformers_the_definitive_guide:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
